interface=virbr1
bind-interfaces

enable-tftp
tftp-root=/srv/tftp

domain=virt.internal
local=/virt.internal/

dhcp-range=192.168.200.2,static,30m

dhcp-match=set:ipxe,175
dhcp-boot=tag:!ipxe,ipxe.efi
dhcp-boot=tag:ipxe,tag:hvst-1,http://192.168.200.1/hvst-1.ipxe
dhcp-boot=tag:ipxe,tag:hvst-2,http://192.168.200.1/hvst-2.ipxe
dhcp-boot=tag:ipxe,tag:hvst-3,http://192.168.200.1/hvst-3.ipxe

dhcp-host=52:54:00:00:00:11,hvst-1,192.168.200.11,set:hvst-1
dhcp-host=52:54:00:00:00:21,hvst-1,192.168.200.12,set:hvst-2
dhcp-host=52:54:00:00:00:31,hvst-1,192.168.200.13,set:hvst-3
